name: pr
on:
  pull_request:
    branches:
      - v1.x
      - v2.x
      - v3.x
jobs:
  build:
    name: Publish latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: matteodelabre
          password: ${{ secrets.CR_PAT }}
      - name: Build images
        run: |
          ./scripts/build .
